services:
  app:
    volumes:
      - ./:/usr/src/app:cached
      - /usr/src/app/node_modules
    environment:
      NODE_ENV: development
    command: sh -c "if [ ! -f node_modules/.bin/nodemon ]; then echo 'Installing dev dependencies...'; npm install; fi && npm run dev"
